### ISSUE TITLE
Errors during Build and release process

### ISSUE THREAD

**Issue by andikrueger** [thegeeklab/hugo-geekdoc#320]
This is a follow up to #317 document the errors I see during build.

The project requires `node-gyp` to be installed so that `npm install` does not fail. I do have a local python setup, which is obviously not enough.

Possible solution:
```powershell
npm install

> ttf2woff2@4.0.4 install C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\ttf2woff2
> ((node-gyp configure && node-gyp build) > builderror.log) || (exit 0)

gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\asd\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\asd\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\asd\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\asd\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:313:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\asd\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\ttf2woff2
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

Possible solution:
```powershell
npm install -g node-gyp
```

**Comment by andikrueger** [comment]
After upgrading npm to v 8.4.1 and an update of node to LTS 16.13.2 and installing node-gyp I see a different error. I opted for  the complete node setup. This includes python, choclately, vc build tools.

```powershell
 npm run build

> geekdoc@1.0.0 build
> run-s prep:clean prep:make svg build:webpack


> geekdoc@1.0.0 prep:clean 
> shx rm -rf build/ static/


> geekdoc@1.0.0 prep:make
> mkdir -p build/icons/ build/fonts/ dist/

The syntax of the command is incorrect.
ERROR: "prep:make" exited with 1.
```

I tested the build in PS5 and PS 7. The error is the same.

**Comment by xoxys** [comment]
`node-gyp` is already a transitive dependency and is getting installed in the project context on `npm install`. The error message shows where it tries to find python and how the location can be configured. Installing `node-gyp` is IMO the wrong way to solve it, but if you are ok with it, and it works for you that's up to you of course.

For the second part of the issue, I have created https://github.com/thegeeklab/hugo-geekdoc/pull/321 would you be able to test this change?

**Comment by andikrueger** [comment]
Thanks for the quick fix. The change in #321 helped. 

This is the output of a current run:

```powershell
npm run build

> geekdoc@1.0.0 build
> run-s prep:clean prep:make svg build:webpack


> geekdoc@1.0.0 prep:clean
> shx rm -rf build/ static/


> geekdoc@1.0.0 prep:make
> shx mkdir -p build/icons/ build/fonts/ dist/


> geekdoc@1.0.0 svg
> run-s svg:*


> geekdoc@1.0.0 svg:sprite
> svg-sprite -C svgsprite.config.json 'src/icons/*.svg'


> geekdoc@1.0.0 svg:font
> svgtofont --sources build/icons/ --output build/fonts/

Font created
SUCCESS SVG font successfully created!
  ╰┈▶ C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\build\fonts\GeekdocIcons.svg
SUCCESS TTF font successfully created!
  ╰┈▶ C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\build\fonts\GeekdocIcons.ttf
SUCCESS EOT font successfully created!
  ╰┈▶ C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\build\fonts\GeekdocIcons.eot
SUCCESS WOFF font successfully created!
  ╰┈▶ C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\build\fonts\GeekdocIcons.woff
SUCCESS WOFF2 font successfully created!
  ╰┈▶ C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\build\fonts\GeekdocIcons.woff2
SUCCESS Svg Symbol font successfully created!
  ╰┈▶ C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\build\fonts\GeekdocIcons.symbol.svg
SUCCESS Created C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\build\fonts\GeekdocIcons.json 
SUCCESS Created React Components.
done!

> geekdoc@1.0.0 build:webpack
> webpack --mode=production

C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\favicons-webpack-plugin\src\index.js:562
    throw new Error(
          ^

Error: Could not find the npm peerDependency "favicons".
Please run:
npm i favicons
 - or -
yarn add favicons

Error: Cannot find module 'favicons'
Require stack:
- C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\favicons-webpack-plugin\src\index.js
- C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\webpack.config.js
- C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\webpack-cli\lib\webpack-cli.js
- C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\webpack-cli\lib\bootstrap.js
- C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\webpack-cli\bin\cli.js
- C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\webpack\bin\webpack.js
    at loadFaviconsLibrary (C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\favicons-webpack-plugin\src\index.js:562:11)
    at FaviconsWebpackPlugin.generateFaviconsWebapp (C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\favicons-webpack-plugin\src\index.js:403:22)   
    at FaviconsWebpackPlugin.generateFavicons (C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\favicons-webpack-plugin\src\index.js:315:21)
    at C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\favicons-webpack-plugin\src\index.js:117:18
    at C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\favicons-webpack-plugin\src\cache.js:155:5
    at CacheFacade.providePromise (C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc\node_modules\webpack\lib\CacheFacade.js:337:24)
ERROR: "build:webpack" exited with 1.
```powershell

**Comment by xoxys** [comment]
That's weird. You are on the main branch and have executed `npm install` right?  Can you post the output of `npm list --depth=1`?

**Comment by andikrueger** [comment]
I ran `npm install` this morning. This is the current output:

```powershell
>npm list --depth=1    
geekdoc@1.0.0 C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc
├─┬ @babel/eslint-parser@7.17.0
│ ├── UNMET DEPENDENCY @babel/core@>=7.11.0
│ ├── eslint-scope@5.1.1
│ ├── eslint-visitor-keys@2.1.0
│ ├── eslint@8.8.0 deduped
│ └── semver@6.3.0
├── @cfworker/json-schema@1.12.1
├─┬ autoprefixer@10.4.2
│ ├── browserslist@4.19.1
│ ├── caniuse-lite@1.0.30001304
│ ├── fraction.js@4.1.2
│ ├── normalize-range@0.1.2
│ ├── picocolors@1.0.0
│ ├── postcss-value-parser@4.2.0
│ └── postcss@8.4.5
├─┬ clipboard@2.0.10
│ ├── good-listener@1.2.2
│ ├── select@1.1.2
│ └── tiny-emitter@2.1.0
├─┬ copy-webpack-plugin@10.2.4
│ ├── fast-glob@3.2.11
│ ├── glob-parent@6.0.2
│ ├── globby@12.2.0
│ ├── normalize-path@3.0.0
│ ├── schema-utils@4.0.0
│ ├── serialize-javascript@6.0.0
│ └── webpack@5.68.0 deduped
├─┬ css-loader@6.6.0
│ ├── icss-utils@5.1.0
│ ├── postcss-modules-extract-imports@3.0.0
│ ├── postcss-modules-local-by-default@4.0.0
│ ├── postcss-modules-scope@3.0.0
│ ├── postcss-modules-values@4.0.0
│ ├── postcss-value-parser@4.2.0 deduped
│ ├── postcss@8.4.5 deduped
│ ├── semver@7.3.5
│ └── webpack@5.68.0 deduped
├─┬ eslint-config-prettier@8.3.0
│ └── eslint@8.8.0 deduped
├─┬ eslint-plugin-prettier@4.0.0
│ ├── eslint@8.8.0 deduped
│ ├── prettier-linter-helpers@1.0.0
│ └── prettier@2.5.1 deduped
├─┬ eslint@8.8.0
│ ├── @eslint/eslintrc@1.0.5
│ ├── @humanwhocodes/config-array@0.9.3
│ ├── ajv@6.12.6
│ ├── chalk@4.1.2
│ ├── cross-spawn@7.0.3
│ ├── debug@4.3.3
│ ├── doctrine@3.0.0
│ ├── escape-string-regexp@4.0.0
│ ├── eslint-scope@7.1.0
│ ├── eslint-utils@3.0.0
│ ├── eslint-visitor-keys@3.2.0
│ ├── espree@9.3.0
│ ├── esquery@1.4.0
│ ├── esutils@2.0.3
│ ├── fast-deep-equal@3.1.3
│ ├── file-entry-cache@6.0.1
│ ├── functional-red-black-tree@1.0.1
│ ├── glob-parent@6.0.2 deduped
│ ├── globals@13.12.0
│ ├── ignore@5.2.0
│ ├── import-fresh@3.3.0
│ ├── imurmurhash@0.1.4
│ ├── is-glob@4.0.3
│ ├── js-yaml@4.1.0
│ ├── json-stable-stringify-without-jsonify@1.0.1
│ ├── levn@0.4.1
│ ├── lodash.merge@4.6.2
│ ├── minimatch@3.0.4
│ ├── natural-compare@1.4.0
│ ├── optionator@0.9.1
│ ├── regexpp@3.2.0
│ ├── strip-ansi@6.0.1
│ ├── strip-json-comments@3.1.1
│ ├── text-table@0.2.0
│ └── v8-compile-cache@2.3.0
├─┬ favicons-webpack-plugin@5.0.2
│ ├── @types/favicons@5.5.0
│ ├── UNMET DEPENDENCY favicons@>= 6.2.0
│ ├── find-root@1.1.0
│ ├── html-webpack-plugin@5.5.0
│ ├── parse-author@2.0.0
│ ├── parse5@6.0.1
│ └── webpack@5.68.0 deduped
├── flexsearch@0.7.21
├─┬ katex@0.15.2
│ └── commander@8.3.0
├─┬ mermaid@8.13.10
│ ├── @braintree/sanitize-url@3.1.0
│ ├── d3@7.3.0
│ ├── dagre-d3@0.6.4
│ ├── dagre@0.8.5
│ ├── dompurify@2.3.4
│ ├── graphlib@2.1.8
│ ├── khroma@1.4.1
│ ├── moment-mini@2.24.0
│ └── stylis@4.0.13
├─┬ npm-run-all@4.1.5
│ ├── ansi-styles@3.2.1
│ ├── chalk@2.4.2
│ ├── cross-spawn@6.0.5
│ ├── memorystream@0.3.1
│ ├── minimatch@3.0.4 deduped
│ ├── pidtree@0.3.1
│ ├── read-pkg@3.0.0
│ ├── shell-quote@1.7.3
│ └── string.prototype.padend@3.1.3
├─┬ postcss-loader@6.2.1
│ ├── cosmiconfig@7.0.1
│ ├── klona@2.0.5
│ ├── postcss@8.4.5 deduped
│ ├── semver@7.3.5
│ └── webpack@5.68.0 deduped
├─┬ prettier-plugin-go-template@0.0.11
│ ├── prettier@2.5.1 deduped
│ └── ulid@2.3.0
├── prettier@2.5.1
├─┬ sass-loader@12.4.0
│ ├── UNMET OPTIONAL DEPENDENCY fibers@>= 3.1.0
│ ├── klona@2.0.5 deduped
│ ├── neo-async@2.6.2
│ ├── UNMET OPTIONAL DEPENDENCY node-sass@^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0
│ ├── sass@1.49.7 deduped
│ └── webpack@5.68.0 deduped
├─┬ sass@1.49.7
│ ├── chokidar@3.5.3
│ ├── immutable@4.0.0
│ └── source-map-js@1.0.2
├─┬ shx@0.3.4
│ ├── minimist@1.2.5
│ └── shelljs@0.8.5
├── store2@2.13.1
├─┬ svg-sprite@1.5.4
│ ├── @xmldom/xmldom@0.7.5
│ ├── async@3.2.3
│ ├── css-selector-parser@1.4.1
│ ├── cssmin@0.4.3
│ ├── cssom@0.5.0
│ ├── glob@7.2.0
│ ├── js-yaml@3.14.1
│ ├── lodash@4.17.21
│ ├── mkdirp@0.5.5
│ ├── mustache@4.2.0
│ ├── phantomjs-prebuilt@2.1.16
│ ├── prettysize@2.0.0
│ ├── svgo@1.3.2
│ ├── vinyl@2.2.1
│ ├── winston@3.5.1
│ ├── xpath@0.0.32
│ └── yargs@15.4.1
├─┬ svgtofont@3.14.0
│ ├── @types/cheerio@0.22.30
│ ├── @types/ejs@3.1.0
│ ├── @types/fs-extra@9.0.13
│ ├── @types/svg2ttf@5.0.1
│ ├── @types/svgo@2.6.1
│ ├── @types/ttf2woff2@2.0.0
│ ├── cheerio@1.0.0-rc.10
│ ├── colors-cli@1.0.28
│ ├── copy-template-dir@1.4.0
│ ├── del@6.0.0
│ ├── ejs@3.1.6
│ ├── fs-extra@10.0.0
│ ├── image2uri@1.0.5
│ ├── move-file@2.1.0
│ ├── svg2ttf@6.0.3
│ ├── svgicons2svgfont@10.0.5
│ ├── svgo@2.8.0
│ ├── ttf2eot@3.0.0
│ ├── ttf2woff@3.0.0
│ ├── ttf2woff2@4.0.4
│ └── yargs@17.3.1
├─┬ webpack-cli@4.9.2
│ ├── @discoveryjs/json-ext@0.5.6
│ ├── @webpack-cli/configtest@1.1.1
│ ├── @webpack-cli/info@1.4.1
│ ├── @webpack-cli/serve@1.6.1
│ ├── colorette@2.0.16
│ ├── commander@7.2.0
│ ├── execa@5.1.1
│ ├── fastest-levenshtein@1.0.12
│ ├── import-local@3.1.0
│ ├── interpret@2.2.0
│ ├── rechoir@0.7.1
│ ├── webpack-merge@5.8.0
│ └── webpack@5.68.0 deduped
├─┬ webpack-manifest-plugin@4.1.1
│ ├── tapable@2.2.1
│ ├── webpack-sources@2.3.1
│ └── webpack@5.68.0 deduped
├─┬ webpack-remove-empty-scripts@0.7.3
│ ├── ansis@1.3.4
│ └── webpack@5.68.0 deduped
└─┬ webpack@5.68.0
  ├── @types/eslint-scope@3.7.3
  ├── @types/estree@0.0.50
  ├── @webassemblyjs/ast@1.11.1
  ├── @webassemblyjs/wasm-edit@1.11.1
  ├── @webassemblyjs/wasm-parser@1.11.1
  ├── acorn-import-assertions@1.8.0
  ├── acorn@8.7.0
  ├── browserslist@4.19.1 deduped
  ├── chrome-trace-event@1.0.3
  ├── enhanced-resolve@5.8.3
  ├── es-module-lexer@0.9.3
  ├── eslint-scope@5.1.1 deduped
  ├── events@3.3.0
  ├── glob-to-regexp@0.4.1
  ├── graceful-fs@4.2.9
  ├── json-parse-better-errors@1.0.2
  ├── loader-runner@4.2.0
  ├── mime-types@2.1.34
  ├── neo-async@2.6.2 deduped
  ├── schema-utils@3.1.1
  ├── tapable@2.2.1 deduped
  ├── terser-webpack-plugin@5.3.0
  ├── watchpack@2.3.1
  └── webpack-sources@3.2.3

npm ERR! code ELSPROBLEMS
npm ERR! missing: @babel/core@>=7.11.0, required by @babel/eslint-parser@7.17.0
npm ERR! missing: favicons@>= 6.2.0, required by favicons-webpack-plugin@5.0.2

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asd\AppData\Local\npm-cache\_logs\2022-02-04T11_14_57_850Z-debug-0.log
```

That is the ouput of a new run for `npm install`

```powershell
npm install

up to date, audited 906 packages in 4s

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
This did not change the output of `npm list`

**Comment by xoxys** [comment]
I guess that's a side effect that you have installed the dependencies with an older npm/nodejs version already. Please remove the entire `node_modules` directory and try again:

```
npm install
npm list --depth=1
npm build
```

**Comment by andikrueger** [comment]
The error is persistent. I deleted the node_modules folder as well as the npm cache...

```
npm list --depth=1
geekdoc@1.0.0 C:\DEV\hugo\hugo-geekdoc-main\hugo-geekdoc
├─┬ @babel/eslint-parser@7.17.0
│ ├── UNMET DEPENDENCY @babel/core@>=7.11.0
│ ├── eslint-scope@5.1.1
│ ├── eslint-visitor-keys@2.1.0
│ ├── eslint@8.8.0 deduped
│ └── semver@6.3.0
├── @cfworker/json-schema@1.12.1
├─┬ autoprefixer@10.4.2
│ ├── browserslist@4.19.1
│ ├── caniuse-lite@1.0.30001304
│ ├── fraction.js@4.1.2
│ ├── normalize-range@0.1.2
│ ├── picocolors@1.0.0
│ ├── postcss-value-parser@4.2.0
│ └── postcss@8.4.5
├─┬ clipboard@2.0.10
│ ├── good-listener@1.2.2
│ ├── select@1.1.2
│ └── tiny-emitter@2.1.0
├─┬ copy-webpack-plugin@10.2.4
│ ├── fast-glob@3.2.11
│ ├── glob-parent@6.0.2
│ ├── globby@12.2.0
│ ├── normalize-path@3.0.0
│ ├── schema-utils@4.0.0
│ ├── serialize-javascript@6.0.0
│ └── webpack@5.68.0 deduped
├─┬ css-loader@6.6.0
│ ├── icss-utils@5.1.0
│ ├── postcss-modules-extract-imports@3.0.0
│ ├── postcss-modules-local-by-default@4.0.0
│ ├── postcss-modules-scope@3.0.0
│ ├── postcss-modules-values@4.0.0
│ ├── postcss-value-parser@4.2.0 deduped
│ ├── postcss@8.4.5 deduped
│ ├── semver@7.3.5
│ └── webpack@5.68.0 deduped
├─┬ eslint-config-prettier@8.3.0
│ └── eslint@8.8.0 deduped
├─┬ eslint-plugin-prettier@4.0.0
│ ├── eslint@8.8.0 deduped
│ ├── prettier-linter-helpers@1.0.0
│ └── prettier@2.5.1 deduped
├─┬ eslint@8.8.0
│ ├── @eslint/eslintrc@1.0.5
│ ├── @humanwhocodes/config-array@0.9.3
│ ├── ajv@6.12.6
│ ├── chalk@4.1.2
│ ├── cross-spawn@7.0.3
│ ├── debug@4.3.3
│ ├── doctrine@3.0.0
│ ├── escape-string-regexp@4.0.0
│ ├── eslint-scope@7.1.0
│ ├── eslint-utils@3.0.0
│ ├── eslint-visitor-keys@3.2.0
│ ├── espree@9.3.0
│ ├── esquery@1.4.0
│ ├── esutils@2.0.3
│ ├── fast-deep-equal@3.1.3
│ ├── file-entry-cache@6.0.1
│ ├── functional-red-black-tree@1.0.1
│ ├── glob-parent@6.0.2 deduped
│ ├── globals@13.12.0
│ ├── ignore@5.2.0
│ ├── import-fresh@3.3.0
│ ├── imurmurhash@0.1.4
│ ├── is-glob@4.0.3
│ ├── js-yaml@4.1.0
│ ├── json-stable-stringify-without-jsonify@1.0.1
│ ├── levn@0.4.1
│ ├── lodash.merge@4.6.2
│ ├── minimatch@3.0.4
│ ├── natural-compare@1.4.0
│ ├── optionator@0.9.1
│ ├── regexpp@3.2.0
│ ├── strip-ansi@6.0.1
│ ├── strip-json-comments@3.1.1
│ ├── text-table@0.2.0
│ └── v8-compile-cache@2.3.0
├─┬ favicons-webpack-plugin@5.0.2
│ ├── @types/favicons@5.5.0
│ ├── UNMET DEPENDENCY favicons@>= 6.2.0
│ ├── find-root@1.1.0
│ ├── html-webpack-plugin@5.5.0
│ ├── parse-author@2.0.0
│ ├── parse5@6.0.1
│ └── webpack@5.68.0 deduped
├── flexsearch@0.7.21
├─┬ katex@0.15.2
│ └── commander@8.3.0
├─┬ mermaid@8.13.10
│ ├── @braintree/sanitize-url@3.1.0
│ ├── d3@7.3.0
│ ├── dagre-d3@0.6.4
│ ├── dagre@0.8.5
│ ├── dompurify@2.3.4
│ ├── graphlib@2.1.8
│ ├── khroma@1.4.1
│ ├── moment-mini@2.24.0
│ └── stylis@4.0.13
├─┬ npm-run-all@4.1.5
│ ├── ansi-styles@3.2.1
│ ├── chalk@2.4.2
│ ├── cross-spawn@6.0.5
│ ├── memorystream@0.3.1
│ ├── minimatch@3.0.4 deduped
│ ├── pidtree@0.3.1
│ ├── read-pkg@3.0.0
│ ├── shell-quote@1.7.3
│ └── string.prototype.padend@3.1.3
├─┬ postcss-loader@6.2.1
│ ├── cosmiconfig@7.0.1
│ ├── klona@2.0.5
│ ├── postcss@8.4.5 deduped
│ ├── semver@7.3.5
│ └── webpack@5.68.0 deduped
├─┬ prettier-plugin-go-template@0.0.11
│ ├── prettier@2.5.1 deduped
│ └── ulid@2.3.0
├── prettier@2.5.1
├─┬ sass-loader@12.4.0
│ ├── UNMET OPTIONAL DEPENDENCY fibers@>= 3.1.0
│ ├── klona@2.0.5 deduped
│ ├── neo-async@2.6.2
│ ├── UNMET OPTIONAL DEPENDENCY node-sass@^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0
│ ├── sass@1.49.7 deduped
│ └── webpack@5.68.0 deduped
├─┬ sass@1.49.7
│ ├── chokidar@3.5.3
│ ├── immutable@4.0.0
│ └── source-map-js@1.0.2
├─┬ shx@0.3.4
│ ├── minimist@1.2.5
│ └── shelljs@0.8.5
├── store2@2.13.1
├─┬ svg-sprite@1.5.4
│ ├── @xmldom/xmldom@0.7.5
│ ├── async@3.2.3
│ ├── css-selector-parser@1.4.1
│ ├── cssmin@0.4.3
│ ├── cssom@0.5.0
│ ├── glob@7.2.0
│ ├── js-yaml@3.14.1
│ ├── lodash@4.17.21
│ ├── mkdirp@0.5.5
│ ├── mustache@4.2.0
│ ├── phantomjs-prebuilt@2.1.16
│ ├── prettysize@2.0.0
│ ├── svgo@1.3.2
│ ├── vinyl@2.2.1
│ ├── winston@3.5.1
│ ├── xpath@0.0.32
│ └── yargs@15.4.1
├─┬ svgtofont@3.14.0
│ ├── @types/cheerio@0.22.30
│ ├── @types/ejs@3.1.0
│ ├── @types/fs-extra@9.0.13
│ ├── @types/svg2ttf@5.0.1
│ ├── @types/svgo@2.6.1
│ ├── @types/ttf2woff2@2.0.0
│ ├── cheerio@1.0.0-rc.10
│ ├── colors-cli@1.0.28
│ ├── copy-template-dir@1.4.0
│ ├── del@6.0.0
│ ├── ejs@3.1.6
│ ├── fs-extra@10.0.0
│ ├── image2uri@1.0.5
│ ├── move-file@2.1.0
│ ├── svg2ttf@6.0.3
│ ├── svgicons2svgfont@10.0.5
│ ├── svgo@2.8.0
│ ├── ttf2eot@3.0.0
│ ├── ttf2woff@3.0.0
│ ├── ttf2woff2@4.0.4
│ └── yargs@17.3.1
├─┬ webpack-cli@4.9.2
│ ├── @discoveryjs/json-ext@0.5.6
│ ├── @webpack-cli/configtest@1.1.1
│ ├── @webpack-cli/info@1.4.1
│ ├── @webpack-cli/serve@1.6.1
│ ├── colorette@2.0.16
│ ├── commander@7.2.0
│ ├── execa@5.1.1
│ ├── fastest-levenshtein@1.0.12
│ ├── import-local@3.1.0
│ ├── interpret@2.2.0
│ ├── rechoir@0.7.1
│ ├── webpack-merge@5.8.0
│ └── webpack@5.68.0 deduped
├─┬ webpack-manifest-plugin@4.1.1
│ ├── tapable@2.2.1
│ ├── webpack-sources@2.3.1
│ └── webpack@5.68.0 deduped
├─┬ webpack-remove-empty-scripts@0.7.3
│ ├── ansis@1.3.4
│ └── webpack@5.68.0 deduped
└─┬ webpack@5.68.0
  ├── @types/eslint-scope@3.7.3
  ├── @types/estree@0.0.50
  ├── @webassemblyjs/ast@1.11.1
  ├── @webassemblyjs/wasm-edit@1.11.1
  ├── @webassemblyjs/wasm-parser@1.11.1
  ├── acorn-import-assertions@1.8.0
  ├── acorn@8.7.0
  ├── browserslist@4.19.1 deduped
  ├── chrome-trace-event@1.0.3
  ├── enhanced-resolve@5.8.3
  ├── es-module-lexer@0.9.3
  ├── eslint-scope@5.1.1 deduped
  ├── events@3.3.0
  ├── glob-to-regexp@0.4.1
  ├── graceful-fs@4.2.9
  ├── json-parse-better-errors@1.0.2
  ├── loader-runner@4.2.0
  ├── mime-types@2.1.34
  ├── neo-async@2.6.2 deduped
  ├── schema-utils@3.1.1
  ├── tapable@2.2.1 deduped
  ├── terser-webpack-plugin@5.3.0
  ├── watchpack@2.3.1
  └── webpack-sources@3.2.3

npm ERR! code ELSPROBLEMS
npm ERR! missing: @babel/core@>=7.11.0, required by @babel/eslint-parser@7.17.0
npm ERR! missing: favicons@>= 6.2.0, required by favicons-webpack-plugin@5.0.2
```

**Comment by andikrueger** [comment]
I get the feeling, this issue is something within npm. There are several reports about issues with `favicons` and `npm`.

I ran the following commands now:
```
npm install favicons@^6.2.0
npm install  @babel/core@>=7.11.0

```

to resolve the issues.

`npm run build` works perfectly now.

**Comment by xoxys** [comment]
Thanks for testing this. But this has to be a Windows specific issue. We use the exact same workflow to build the theme on CI and we use plain NodeJS docker images.

**Comment by andikrueger** [comment]
It is not worth to investigate further. 

I did delete node_modules again and ran `npm install`. This time, favicons and babel/core are installed properly. Feels like a windows/system specific issue.

Thank you for you great support!
